### ISSUE TITLE
Allow users to sign in/up.

### ISSUE THREAD

**Issue by DanielRailean** [SEP6-A2022/SEP6#13]
We need a way to allow users to sign up. Ideally they could do that using their email + password or using oauth2.

## Tasks to complete

- [ ] Create a sign up page
- [ ] Create a sign in page
- [ ] Add some oauth providers to those pages.

## Acceptance criteria

- [ ] Users can sign up using email+password
- [ ] Users can sign up using oauth.
