### ISSUE TITLE
Add a page to display info about directors/actors

### ISSUE THREAD

**Issue by DanielRailean** [SEP6-A2022/SEP6#14]
This page should include a list where the actor/director was involved.
It should also include an average of the stars of those movies.

The pages can be identical and can have an url like `/person/{name}` or `/person/{id}`

## Tasks to complete

- [ ] Create the actor/director page mentioned above.

## Acceptance criteria

- [ ] The page displays the average rating.
- [ ] The page displays the movies a star was involved in.
