### ISSUE TITLE
Enable lazy loading of movie info / person info

### ISSUE THREAD

**Issue by DanielRailean** [SEP6-A2022/SEP6#15]
As the current dataset might be incomplete, as we miss movie image, description sometimes we might even miss the movie entirely, we need a way to `lazy-load` that info to our database.

This for the image and description this can be easily achieved by calling some API if the info is missing and then saving the info in the db. Next time we can use the db info.

For the missing movies/persons, the best way would be to lazy-load them on access by link / during search, but an alternative approach can also be developed.

## Tasks to complete

- [x] Implement the mechanism described above.

## Acceptance criteria

- [x] Movies info is lazy-loaded
- [x] Movies/Persons are lazy loaded.
