### ISSUE TITLE
We need a way to contribute information about the movies.

### ISSUE THREAD

**Issue by DanielRailean** [SEP6-A2022/SEP6#9]
We need a way to contribute information about the movies because it can simplify the work of the administrators and it's mentioned in the project requirements.

## Tasks to complete
- [ ] Add a description row to the movies table
- [ ] Allow users to contribute to that table 
- [ ] Allow admins to accept user contributions

## Acceptance criteria
- [ ] Users can contribute to the movie info.
- [ ] Admins can accept/deny contributions.

**Comment by DanielRailean** [comment]
Depends on : 
- https://github.com/SEP6-A2022/SEP6/issues/13

so that needs to be cleared first

**Comment by DanielRailean** [comment]
Seems like it's not part of the must requirements, so user contributions won't be implemented for now. 

The viewing or access part will be implemented as part of lazy loading data.
